### PR TITLE
First pass at creating a more dynamic frontend

### PR DESCRIPTION
**Pull request by tsmarvin**
I re-arranged the existing functions, removed some from the base install, and then created New-SiqOSSpecificFunctions to create the rest of the available functions on a per-OS basis.

Feel free to pick and choose what you want to accept! I won't mind.

### CODE REVIEW

**Comment by awakecoding** [comment]
@tsmarvin here are few thoughts about things that would eventually need to be improved:

platform-specific tables: the original osquery table schema encodes supported platforms, we should try and find a way to do the same in siquery to easily tell which ones are available for the current platform. I am not sure how well we can get dynamic function exporting to work, anything dynamic inside the psd1 can make static analysis more difficult. I think PSGallery uses the nupkg tag field with the whole list of exported functions in its search, and since we can only publish one nupkg for all platforms, we'd likely have to export them all. I'm thinking maybe we should export all tables but throw an unsupported platform exception? I know it's not the best, but maybe it would be the simplest.

one-function-per-file: this is a performance issue for a lot of ps1 files but we don't care much about this problem because we'll eventually rewrite all of them to C#. There is also the possibility of combining all ps1 files into one large ps1 files while "building" the final PowerShell module. Performance degrades even further for a lot of code signed files.

table schema information: we should export functions to return the list of currently supported tables (dynamic) along with the individual table schema. osquery returns this schema information as SQL, we just want to return the same kind of information as PowerShell objects (can map directly to a JSON schema)

**Comment by awakecoding** [comment]
@tsmarvin for the current pull request, I would have just one thing to fix: the snake_case to PascalCase conversion. I noticed that the generated cmdlets don't correctly convert the casing for the tables names, such that process_memory_map becomes Processmemorymap instead of ProcessMemoryMap. The ConvertTo-PascalCase should handle the conversion correctly:

`ConvertTo-PascalCase 'process_memory_map'`

**Comment by tsmarvin** [comment]
@awakecoding  here are few thoughts about things that would eventually need to be improved:

`platform-specific tables:` This was the main reason I decided to build New-SiqOSSpecificFunctions. I didn't want the installed module to list a bunch of available commands for functions that aren't relevant to this OS. To be honest I wasn't particularly happy about my implementation of it but really just wanted to provide a jump off point for discussion/future code. 
I really just don't like the idea of shipping a module that has a bunch of useless commands on all 3 OS's. 

My alternative thought for this was to actually make a "new" edition of Get-ComputerInfo with dynamic parameters (yuck) for the available info on each OS. That has it's own assorted problems though.

`one-function-per-file:` I'm aware that this is a performance issue in the long term - I just personally prefer it from an organization perspective while developing. I'm a big fan of doing the combines as part of the final module build/publish steps.

`table schema information:` I think this info should be pulled dynamically, per OS, and should be used to build more functional cmdlets parameters. Not sure on the best implementation methods though. I really don't like dynamic parameters. 

`final notes:` I'll check out the issue with ConvertTo-PascalCase when I get done with work today. I want to say it was working on my machine but I may just not have noticed.

**Comment by awakecoding** [comment]
I agree we should try exporting only supported tables for the current platform. Let's dynamically filter the functions we export and see what kind of issues we encounter, if any. Worst case we'll deal with the PSGallery nupkg tag differently, as it lists the functions exported by the module in a static list.

This being said, I don't think we want dynamic parameters (I've heard a lot of bad things about them), or tables that have the same name but use different parameters based on the platform. I really think we should enforce some kind of table schema like osquery and build our functions to match it. This will allow us to provide table-specific Get-SiqMyTable functions while also exposing the entire schema for discovery (list all tables, list table schema, etc).

The [original schema format](https://github.com/osquery/osquery/tree/master/specs) used by osquery is very SQL-like, so I'm thinking we could write a PowerShell script to process and transform it into a simpler JSON-like schema. The same schema is used to generate the [osquery schema section of the website](https://www.osquery.io/schema/4.8.0/) in an easier to consult format. Once we've successfully transformed it for our needs, we could easily automate a lot of boilerplate code, and then just implement useful tables one by one without having to re-design them from scratch.

When we got the siquery project started, I think they only had around 100 tables, they now have over 270. The biggest issue with trying to gather a large collection of system information tables is figuring out what it should be in a way that doesn't change very often (and therefore breaks backward compatibility). They've got their tables battle-tested and driven by actual need, so let's tap into it and then add our own extensions on top of it to complement what isn't there.

There is one potentially annoying thing that can still be automated: snake_case vs PascalCase. The cool thing about pure snake_case is that it can always be reliably converted to PascalCase, but the inverse doesn't always work well if you didn't resist the urge of keeping a few uppercase letters for short acronyms. For instance, ip_address becomes IpAddress, but if you've written it IPAddress, it would automatically convert to i_p_address with no easy way to figure out it should have been ip_address.

I suggest we keep both the snake_case and PascalCase and generate mapping tables if we want to handle both, or handle the conversion at runtime (just a bit slower, but still). The important part is we can automatically do it from the schema.

**Comment by tsmarvin** [comment]
Per our twitter discussion I added an initial function to be able to get the schema information of a given table. 
This was just a first pass and I didn't bother moving it to public yet as it still needs some refinement (though it gets all the data on my system currently). 

I also fixed the pascal case issue.

I'm going to be fairly busy tomorrow but will likely have time to look at the project again on Sunday in the evening.

**Comment by tsmarvin** [comment]
I'm not sure what your merge policy is - so for now I'll just leave this in the fork. Feel free to merge if you're comfortable with that.

**Comment by awakecoding** [comment]
@tsmarvin I was unsure about which way to go forward after yesterday's discussion - let me merge this PR and then start making changes on top of it. The current siquery executable can dump the SQL schema, I didn't necessarily expect you to parse it like that, it's impressive! We can definitely use it to automatically generate an initial JSON schema on our side.

Today is my last day before 4 weeks of vacation - since the next day you'll have time to work on it is Sunday, I'll go ahead and try to make as much of the structural changes right away today. I'll remove the one-function-per-table stuff and get the JSON schema definitions in place for the existing tables.

**Pull request merged**
